# Generated by Django 5.1.11 on 2025-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='Leave empty for default brand (no subdomain)', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default brand for main domain')),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('primary_color', models.CharField(default='#0d6efd', help_text='Brand primary color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Brand secondary color (hex)', max_length=7)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_brand')],
            },
        ),
    ]
