# Generated by Django 5.1.11 on 2025-08-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brandearnings_brandimagecategory_brandimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='headline',
            field=models.CharField(blank=True, help_text='Main headline for homepage', max_length=500),
        ),
    ]
