# Generated by Django 5.2.5 on 2025-08-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brand_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='primary_color',
            field=models.CharField(default='#007bff', help_text='Brand primary color (hex)', max_length=7),
        ),
    ]
