# Generated by Django 5.2.5 on 2025-08-25 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brand_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('business_type', models.CharField(blank=True, choices=[('sports_team', 'Sports Team/League'), ('school', 'School/University'), ('corporate', 'Corporate/Company'), ('nonprofit', 'Non-Profit Organization'), ('retail', 'Retail/E-commerce'), ('other', 'Other')], max_length=50)),
                ('expected_volume', models.CharField(blank=True, choices=[('1-50', '1-50 items'), ('50-100', '50-100 items'), ('100-500', '100-500 items'), ('500-1000', '500-1000 items'), ('1000+', '1000+ items')], max_length=20)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('contacted', 'Contacted')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about this request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_request', to='brands.brand')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Request',
                'verbose_name_plural': 'Partner Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
