# Generated by Django 5.2.5 on 2025-08-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_partnerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Background image file', upload_to='brand_backgrounds/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail (auto-generated if empty)', upload_to='brand_backgrounds/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default background for this brand')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Brand Background',
                'verbose_name_plural': 'Brand Backgrounds',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
