# Generated by Django 5.1.11 on 2025-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsubmission',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportsubmission',
            name='category',
            field=models.CharField(choices=[('orders', 'Orders'), ('account', 'Account'), ('designing', 'Designing'), ('request_model', 'Request Model'), ('website', 'Website Problem'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
