# Generated by Django 5.2.5 on 2025-08-23 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0004_alter_brand_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.IntegerField()),
                ('data', models.JSONField()),
                ('thumbnail_front', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_back', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_left', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_right', models.URLField(blank=True, max_length=500, null=True)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DesignShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='designer.design')),
            ],
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product', models.CharField(max_length=100)),
                ('design_data', models.JSONField()),
                ('thumbnail_front', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_back', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_left', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_right', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to='brands.brand')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
