# Generated by Django 5.2.5 on 2025-08-26 23:57

import designer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for guest users', max_length=40, null=True)),
                ('image', models.ImageField(help_text='Original uploaded image', upload_to=designer.models.design_image_upload_path)),
                ('name', models.CharField(help_text='Display name for the image', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('filetype', models.CharField(blank=True, help_text='File extension/type (jpg, png, etc.)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who uploaded the image (null for guest users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='designer_de_user_id_5854ee_idx'), models.Index(fields=['session_id'], name='designer_de_session_d37418_idx'), models.Index(fields=['-created_at'], name='designer_de_created_569a07_idx')],
            },
        ),
    ]
