# Generated by Django 5.2.5 on 2025-08-27 20:43

import designer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_designimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='design',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='design',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session ID for guest users', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='thumbnail_back',
            field=models.ImageField(blank=True, null=True, upload_to=designer.models.design_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='design',
            name='thumbnail_front',
            field=models.ImageField(blank=True, null=True, upload_to=designer.models.design_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='design',
            name='thumbnail_left',
            field=models.ImageField(blank=True, null=True, upload_to=designer.models.design_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='design',
            name='thumbnail_right',
            field=models.ImageField(blank=True, null=True, upload_to=designer.models.design_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='design',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created the design (null for guest users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='design',
            name='brand',
        ),
    ]
