# Generated by Django 5.2.5 on 2025-08-28 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_add_brand_background_model'),
        ('designer', '0003_update_design_model_for_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand associated with this design', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='brands.brand'),
        ),
    ]
