"""
Static product data migrated from PHP data files
"""

# Products data
products = [
    {
        'id': 0,
        'name': 'Pro Series Hoodie (Fleece Lined) FULL ZIP',
        'modelLink': '/static/models/pro-series-hoodie-full-zip.glb',
        'thumbnail': '/static/thumbnails/pro-series-hoodie-full-zip.png',
        'categories': ['Hoodies'],
        'description': 'Premium fleece-lined hoodie with full zip and customizable pockets. Perfect for staying warm while showcasing your custom designs.',
        'initialLayer': 'Front',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 100,
            3: 90,
            5: 80,
            10: 70,
            20: 60,
        },
        'initialBumpmap': 'Polyester',
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            '100% premium cotton blend',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Back', 'Left_Sleeve', 'Right_Sleeve', 'Hood', 'Pockets'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Front', 'Left_Sleeve', 'Right_Sleeve', 'Hood', 'Pockets'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Hood': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve', 'Pockets'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Front', 'Back', 'Right_Sleeve', 'Hood', 'Pockets'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Hood', 'Pockets'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Pockets': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve', 'Hood'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Strings': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'linkedBumpmaps': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zip': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'linkedBumpmaps': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zip_Cloth': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'linkedBumpmaps': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        }
    },
    {
        'id': 5,
        'name': 'Big Golf Towel',
        'modelLink': '/static/models/big-golf-towel.glb',
        'thumbnail': '/static/thumbnails/big-golf-towel.png',
        'categories': ['Towels'],
        'description': 'Premium large golf towel designed for superior performance on the course. Highly absorbent with quick-dry technology and convenient clip attachment.',
        'initialLayer': 'Front',
        'initialBumpmap': 'Cloth',
        'canOrder': True,
        'sizes': ['16" x 24"', '24" x 48"'],
        'prices': {1: 25, 5: 22, 10: 20, 25: 18},
        'supportedBumpmaps': [],
        'productDetails': [
            'Premium terry cloth material',
            'Highly absorbent',
            'Quick-drying technology',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0.27, 'maxX': 0.8, 'minY': 0.08, 'maxY': 0.92,
                'initialColor': '40C057',
                'bumpMap': True,
                'linkedColors': ['Back'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Back': {
                'minX': 0.15, 'maxX': 0.68, 'minY': 0.08, 'maxY': 0.92,
                'initialColor': '40C057',
                'bumpMap': True,
                'linkedColors': ['Front'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Clip': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'fafafa',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Stiching': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'fafafa',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Grommet': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'fafafa',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
        },
    },
    {
        'id': 1,
        'name': 'Pro Series Hoodie (Fleece Lined)',
        'modelLink': '/static/models/pro-series-hoodie.glb',
        'thumbnail': '/static/thumbnails/pro-series-hoodie.png',
        'categories': ['Hoodies'],
        'description': 'Cozy fleece-lined pullover hoodie designed for all-day comfort. Features a kangaroo pocket and soft drawstring hood for the perfect custom fit.',
        'initialLayer': 'Front',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 90,
            3: 80,
            5: 70,
            10: 65,
            20: 55,
        },
        'initialBumpmap': 'Polyester',
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            '100% premium fleece material',
            'Pre-shrunk for perfect fit', 
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Left_Sleeve', 'Right_Sleeve', 'Pocket', 'Hood'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Left_Sleeve', 'Right_Sleeve', 'Pocket', 'Hood'],
            },
            'Hood': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Left_Sleeve', 'Right_Sleeve', 'Pocket', 'Back'],
            },
            'Pocket': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Left_Sleeve', 'Right_Sleeve', 'Hood', 'Back'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Pocket', 'Right_Sleeve', 'Hood', 'Back'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Pocket', 'Left_Sleeve', 'Hood', 'Back'],
            },
            'Strings': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
    {
        'id': 7,
        'name': 'Elite Series LS Hood (SPF 40)',
        'modelLink': '/static/models/elite-series-ls-hood.glb',
        'thumbnail': '/static/thumbnails/elite-series-ls-hood.png',
        'categories': ['Hoodies'],
        'description': 'Lightweight SPF 40 hooded long sleeve perfect for outdoor activities. Provides sun protection while maintaining breathability and comfort.',
        'initialLayer': 'Front',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 80,
            3: 70,
            5: 60,
            10: 55,
            20: 45,
        },
        'initialBumpmap': 'Polyester',
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'Lightweight SPF 40 polyester blend',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Outside_Hood', 'Inside_Hood', 'Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Outside_Hood', 'Inside_Hood', 'Front', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Outside_Hood': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Front', 'Inside_Hood', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Inside_Hood': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Front', 'Outside_Hood', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Front', 'Outside_Hood', 'Inside_Hood', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Front', 'Outside_Hood', 'Inside_Hood', 'Left_Sleeve'],
            },
        },
    },
    {
        'id': 2,
        'name': 'Elite Series Long Sleeve',
        'modelLink': '/static/models/elite-series-long-sleeve.glb',
        'thumbnail': '/static/thumbnails/elite-series-long-sleeve.png',
        'categories': ['Jerseys'],
        'description': 'Elite performance long sleeve jersey with moisture-wicking technology. Perfect for teams and athletes who demand superior comfort during intense activities.',
        'initialLayer': 'Front',
        'initialBumpmap': 'Polyester',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 75,
            3: 65,
            5: 60,
            10: 55,
            20: 45,
        },
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'Premium moisture-wicking polyester',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Neck': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Left_Sleeve'],
            },
            'Zip_Stiching': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Fabric': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Pull': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
    {
        'id': 18,
        'name': 'Pro Series Long Sleeve',
        'modelLink': '/static/models/pro-series-long-sleeve.glb',
        'thumbnail': '/static/thumbnails/pro-series-long-sleeve.png',
        'categories': ['Jerseys'],
        'description': 'Pro-grade long sleeve jersey engineered for peak performance and durability. Features moisture-wicking fabric that keeps you dry and comfortable all day long.',
        'initialLayer': 'Front',
        'initialBumpmap': 'Polyester',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 75,
            3: 65,
            5: 60,
            10: 55,
            20: 45,
        },
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'High-performance polyester jersey',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Neck': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Left_Sleeve'],
            },
            'Stitches': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Fabric': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zip': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Pull': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
    {
        'id': 19,
        'name': 'Button Polo Long Sleeve',
        'modelLink': '/static/models/button-polo-long-sleeve.glb',
        'thumbnail': '/static/thumbnails/button-polo-long-sleeve.png',
        'categories': ['Jerseys'],
        'description': 'Classic button polo with long sleeves combining professional style with athletic performance. Perfect for team uniforms and corporate events.',
        'initialLayer': 'Front',
        'initialBumpmap': 'Polyester',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 75,
            3: 65,
            5: 60,
            10: 55,
            20: 45,
        },
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'Premium button polo polyester',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Neck': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Left_Sleeve'],
            },
            'Button_1': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Button_2': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Button_3': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Button_Fabric_1': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Button_Fabric_2': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
    {
        'id': 20,
        'name': 'Zipper Polo Long Sleeve',
        'modelLink': '/static/models/zipper-polo-long-sleeve.glb',
        'thumbnail': '/static/thumbnails/zipper-polo-long-sleeve.png',
        'categories': ['Jerseys'],
        'description': 'Modern zipper polo long sleeve designed for versatility and comfort. Features moisture-wicking fabric perfect for active wear and team sports.',
        'initialLayer': 'Front',
        'initialBumpmap': 'Polyester',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 75,
            3: 65,
            5: 60,
            10: 55,
            20: 45,
        },
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'Premium zipper polo polyester',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Neck': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Left_Sleeve'],
            },
            'Stitches': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Fabric': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zip': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Pull': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
    {
        'id': 3,
        'name': 'Crew Neck Long Sleeve',
        'modelLink': '/static/models/crew-neck-long-sleeve.glb',
        'thumbnail': '/static/thumbnails/crew-neck-long-sleeve.png',
        'categories': ['Jerseys'],
        'description': 'Classic crew neck long sleeve jersey offering timeless style and athletic functionality. Ideal for layering and custom team designs.',
        'initialLayer': 'Front',
        'initialBumpmap': 'Polyester',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 70,
            3: 60,
            5: 55,
            10: 50,
            20: 40,
        },
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'Classic crew neck polyester blend',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve'],
            },
        },
    },
    {
        'id': 9,
        'name': 'Crew Neck Short Sleeve',
        'categories': ['Jerseys', 'Tees'],
        'description': 'Lightweight crew neck short sleeve jersey perfect for warm weather sports and activities. Features breathable fabric for optimal performance.',
        'modelLink': '/static/models/crew-neck-short-sleeve.glb',
        'thumbnail': '/static/thumbnails/crew-neck-short-sleeve.png',
        'initialLayer': 'Front',
        'initialBumpmap': 'Polyester',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 65,
            3: 60,
            5: 50,
            10: 45,
            20: 35,
        },
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'Lightweight crew neck polyester',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve'],
            },
        },
    },
    {
        'id': 10,
        'name': 'Pro Series Short Sleeve',
        'modelLink': '/static/models/pro-series-short-sleeve.glb',
        'thumbnail': '/static/thumbnails/pro-series-short-sleeve.png',
        'categories': ['Jerseys', 'Tees'],
        'description': 'Premium short sleeve tee that combines classic comfort with custom style. Perfect for everyday wear and showcasing your personal expression.',
        'initialLayer': 'Front',
        'initialBumpmap': 'Polyester',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 65,
            3: 60,
            5: 55,
            10: 50,
            20: 40,
        },
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'Premium cotton-polyester blend',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Collar', 'Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Collar', 'Front', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Collar', 'Front', 'Back', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Collar', 'Front', 'Back', 'Left_Sleeve'],
            },
            'Collar': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Right_Sleeve', 'Front', 'Back', 'Left_Sleeve'],
            },
            'Stitching': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': ['Zipper_Fabric'],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Fabric': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': ['Zipper'],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Pull': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
    {
        'id': 21,
        'name': 'Button Polo Short Sleeve',
        'modelLink': '/static/models/button-polo-short-sleeve.glb',
        'thumbnail': '/static/thumbnails/button-polo-short-sleeve.png',
        'categories': ['Jerseys'],
        'description': 'Professional button polo short sleeve perfect for corporate teams and casual athletic wear. Combines classic styling with performance fabric.',
        'initialLayer': 'Front',
        'initialBumpmap': 'Polyester',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 65,
            3: 60,
            5: 55,
            10: 50,
            20: 40,
        },
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'Classic button polo polyester',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Neck': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Left_Sleeve'],
            },
            'Button_1': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Button_2': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Button_3': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Fabric_1': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Fabric_2': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
    {
        'id': 22,
        'name': 'Zipper Polo Short Sleeve',
        'modelLink': '/static/models/zipper-polo-short-sleeve.glb',
        'thumbnail': '/static/thumbnails/zipper-polo-short-sleeve.png',
        'categories': ['Jerseys'],
        'description': 'Contemporary zipper polo short sleeve designed for active lifestyles. Features moisture-wicking technology and a sleek modern fit.',
        'initialLayer': 'Front',
        'initialBumpmap': 'Polyester',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 65,
            3: 60,
            5: 55,
            10: 50,
            20: 40,
        },
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'Performance zipper polo polyester',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Neck': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Left_Sleeve'],
            },
            'Stitches': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Fabric': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Pull': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
    {
        'id': 23,
        'name': 'Elite Series Short Sleeve',
        'modelLink': '/static/models/elite-series-short-sleeve.glb',
        'thumbnail': '/static/thumbnails/elite-series-short-sleeve.png',
        'categories': ['Jerseys', 'Tees'],
        'description': 'Elite performance short sleeve jersey engineered for serious athletes. Features advanced moisture-wicking and superior comfort for competitive sports.',
        'initialLayer': 'Front',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 65,
            3: 60,
            5: 55,
            10: 50,
            20: 40,
        },
        'initialBumpmap': 'Polyester',
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            'Elite performance polyester blend',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Back', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Neck', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Neck': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve'],
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Right_Sleeve'],
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
                'linkedBumpmaps': ['Front', 'Back', 'Neck', 'Left_Sleeve'],
            },
            'Stitches': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Fabric': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zip': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Zipper_Pull': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
    {
        'id': 6,
        'name': 'Small Golf Towel',
        'modelLink': '/static/models/small-golf-towel.glb',
        'thumbnail': '/static/thumbnails/small-golf-towel.png',
        'categories': ['Towels'],
        'description': 'Compact golf towel perfect for on-the-go use and easy bag storage. Features premium terry cloth material with excellent absorption and quick-drying properties.',
        'initialLayer': 'Front',
        'initialBumpmap': 'Cloth',
        'canOrder': True,
        'sizes': ['12" x 16"', '16" x 20"'],
        'prices': {1: 18, 5: 16, 10: 14, 25: 12},
        'supportedBumpmaps': [],
        'productDetails': [
            'Premium terry cloth material',
            'Highly absorbent',
            'Quick-drying technology',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0.1, 'maxX': 0.9, 'minY': 0.1, 'maxY': 0.9,
                'initialColor': '40C057',
                'bumpMap': True,
                'linkedColors': ['Back'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Back': {
                'minX': 0.1, 'maxX': 0.9, 'minY': 0.1, 'maxY': 0.9,
                'initialColor': '40C057',
                'bumpMap': True,
                'linkedColors': ['Front'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Clip': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'fafafa',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Stiching': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'fafafa',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Grommet': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'fafafa',
                'bumpMap': False,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
        },
    },
    {
        'id': 4,
        'name': 'Cornhole Board',
        'modelLink': '/static/models/cornhole-board.glb',
        'thumbnail': '/static/thumbnails/cornhole-board.png',
        'categories': ['Home'],
        'description': 'Professional-grade cornhole board built for years of backyard fun and tournament play. Features premium plywood construction with weather-resistant finish.',
        'initialLayer': 'Face',
        'initialBumpmap': 'Marble',
        'canOrder': True,
        'sizes': ['2\' x 4\' Tournament Size', '1.5\' x 3\' Compact Size'],
        'prices': {1: 150, 2: 140, 5: 125, 10: 110},
        'supportedBumpmaps': [],
        'productDetails': [
            'Premium plywood construction',
            'Weather-resistant finish',
            'Durable construction',
            'Easy to clean',
            'Long-lasting vibrant colors',
            'Fade-resistant printing'
        ],
        'meshSettings': {
            'Base': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Border': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': '2C3D81',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Legs': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Face': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
    {
        'id': 8,
        'name': 'Mug',
        'modelLink': '/static/models/mug.glb',
        'thumbnail': '/static/thumbnails/mug.png',
        'categories': ['Home'],
        'description': 'Durable ceramic mug perfect for your morning coffee and custom designs. Microwave and dishwasher safe with fade-resistant printing.',
        'initialLayer': 'Surface',
        'initialBumpmap': 'Marble',
        'canOrder': True,
        'sizes': ['11 oz Standard', '15 oz Large'],
        'prices': {1: 20, 5: 18, 10: 15, 25: 12},
        'supportedBumpmaps': [],
        'productDetails': [
            'High-quality ceramic material',
            'Microwave and dishwasher safe',
            'Durable construction',
            'Easy to clean',
            'Long-lasting vibrant colors',
            'Fade-resistant printing'
        ],
        'meshSettings': {
            'Surface': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': ['Base'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Base': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': ['Surface'],
                'alias': 'Surface',
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
        },
    },
    {
        'id': 11,
        'name': 'Tumbler',
        'modelLink': '/static/models/tumbler.glb',
        'thumbnail': '/static/thumbnails/tumbler.png',
        'categories': ['Home'],
        'description': 'Keep beverages at the perfect temperature with this insulated stainless steel tumbler. Features double-wall construction and comes with a convenient straw.',
        'initialLayer': 'Surface',
        'initialBumpmap': 'Marble',
        'canOrder': True,
        'sizes': ['20 oz Standard', '30 oz Large'],
        'prices': {1: 25, 5: 22, 10: 20, 25: 18},
        'supportedBumpmaps': [],
        'productDetails': [
            'Stainless steel construction',
            'Double-wall insulation',
            'Durable construction',
            'Easy to clean',
            'Long-lasting vibrant colors',
            'Fade-resistant printing'
        ],
        'meshSettings': {
            'Surface': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': ['Base'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Base': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'alias': 'Surface',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Straw': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': False,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
            'Cap': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'canSelect': True,
                'canAddImages': False,
                'canChangeColor': True,
                'canChangeBumpmap': False,
            },
        },
    },
]

# Bumpmap textures data
bumpmap_textures = {
    'none': {
        'name': 'No Texture',
        'link': None,
        'thumbnail': '/static/images/no-texture.svg',
        'scale': 0,
        'size': 1,
        'roughness': 1,
        'metalness': 0,
    },
    'Lace': {
        'name': 'Lace',
        'link': '/static/bumpmaps/fabric2.png',
        'scale': 0.3,
        'size': 3,
        'roughness': 0.9,
        'metalness': 0,
        'thumbnail': '/static/bumpmaps/lace_thumbnail.jpg',
    },
    'Lace2': {
        'name': 'Lace Pattern 2',
        'link': '/static/bumpmaps/lace2.png',
        'scale': 0.5,
        'size': 2,
        'roughness': 0.8,
        'metalness': 0,
        'thumbnail': '/static/bumpmaps/lace2_thumbnail.jpg',
    },
    'Lace3': {
        'name': 'Lace Pattern 3',
        'link': '/static/bumpmaps/lace3.png',
        'scale': 0.4,
        'size': 2.5,
        'roughness': 0.85,
        'metalness': 0,
        'thumbnail': '/static/bumpmaps/lace3_thumbnail.jpg',
    },
    'Cloth': {
        'name': 'Upholstery Cloth',
        'link': '/static/bumpmaps/grey-upholstery_height.png',
        'thumbnail': '/static/bumpmaps/grey-upholstery_height.png',
        'scale': 0.2,
        'size': 4,
        'roughness': 0.95,
        'metalness': 0,
    },
    'Fabric': {
        'name': 'Basic Fabric',
        'link': '/static/bumpmaps/fabric.png',
        'thumbnail': '/static/bumpmaps/fabric.png',
        'scale': 0.25,
        'size': 3.5,
        'roughness': 0.9,
        'metalness': 0,
    },
    'Fabric3': {
        'name': 'Fabric Pattern',
        'link': '/static/bumpmaps/fabric3.png',
        'thumbnail': '/static/bumpmaps/fabric3_thumbnail.jpg',
        'scale': 0.3,
        'size': 3,
        'roughness': 0.85,
        'metalness': 0,
    },
    'Polyester': {
        'name': 'Polyester',
        'link': '/static/bumpmaps/polyester.png',
        'thumbnail': '/static/bumpmaps/polyester_thumbnail.jpg',
        'scale': 0.0005,
        'size': 0.2,
        'roughness': 1,
        'metalness': 0,
    },
    'Polyester2': {
        'name': 'Polyester 2',
        'link': '/static/bumpmaps/polyester2.png',
        'thumbnail': '/static/bumpmaps/polyester2_thumbnail.jpg',
        'scale': 0.2,
        'size': 4,
        'roughness': 1,
        'metalness': 0,
    },
    'Metal': {
        'name': 'Metal',
        'link': '/static/bumpmaps/metal.png',
        'thumbnail': '/static/bumpmaps/metal_thumbnail.jpg',
        'scale': 0.1,
        'size': 5,
        'roughness': 0.3,
        'metalness': 0.8,
    },
    'Marble': {
        'name': 'Marble',
        'link': '/static/bumpmaps/marble.png',
        'thumbnail': '/static/bumpmaps/marble.png',
        'scale': 0.08,
        'size': 6,
        'roughness': 0.2,
        'metalness': 0.05,
    },
    'Wood': {
        'name': 'Wood',
        'link': '/static/bumpmaps/wood.png',
        'thumbnail': '/static/bumpmaps/wood_thumbnail.jpg',
        'scale': 0.15,
        'size': 4,
        'roughness': 0.8,
        'metalness': 0,
    },
    'Burlap': {
        'name': 'Burlap',
        'link': '/static/bumpmaps/burlap.png',
        'thumbnail': '/static/bumpmaps/burlap_thumbnail.jpg',
        'scale': 0.35,
        'size': 2.5,
        'roughness': 0.95,
        'metalness': 0,
    },
    'Hedge': {
        'name': 'Hedge',
        'link': '/static/bumpmaps/hedge.png',
        'thumbnail': '/static/bumpmaps/hedge_thumbnail.jpg',
        'scale': 0.3,
        'size': 3,
        'roughness': 0.9,
        'metalness': 0,
    },
    'Honeycomb': {
        'name': 'Honeycomb',
        'link': '/static/bumpmaps/honeycomb.png',
        'thumbnail': '/static/bumpmaps/honeycomb_thumbnail.png',
        'scale': 0.25,
        'size': 3.5,
        'roughness': 0.6,
        'metalness': 0.2,
    },
    'Knitted': {
        'name': 'Knitted',
        'link': '/static/bumpmaps/knitted.png',
        'thumbnail': '/static/bumpmaps/knitted_thumbnail.jpg',
        'scale': 0.3,
        'size': 3,
        'roughness': 0.9,
        'metalness': 0,
    },
    'Micromesh': {
        'name': 'Micromesh',
        'link': '/static/bumpmaps/micromesh.png',
        'thumbnail': '/static/bumpmaps/micromesh_thumbnail.jpg',
        'scale': 0.003,
        'size': 2.2,
        'roughness': 1,
        'metalness': 0,
    },
    'Military': {
        'name': 'Military',
        'link': '/static/bumpmaps/military.png',
        'thumbnail': '/static/bumpmaps/military_thumbnail.jpg',
        'scale': 0.22,
        'size': 3.8,
        'roughness': 0.8,
        'metalness': 0,
    },
    'Nylon': {
        'name': 'Nylon',
        'link': '/static/bumpmaps/nylon.png',
        'thumbnail': '/static/bumpmaps/nylon.png',
        'scale': 0.28,
        'size': 3.2,
        'roughness': 0.7,
        'metalness': 0.1,
    },
}

# Fonts data
fonts = [
    'Roboto',
    'Oswald',
    'Bebas Neue',
    'Anton',
    'Caveat',
    'Permanent Marker',
    'Orbitron',
    'Yellowtail',
    'Bangers',
    'Faster One',
    'Racing Sans One',
    'Rubik Moonrocks',
    'DM Serif Text',
    'Dancing Script',
    'Seymour One',
    'Black Ops One',
    'Shrikhand',
    'Yatra One',
    'Alex Brush',
    'Pacifico',
    'Kaushan Script',
    'Rock Salt',
    'Six Caps',
    'Gochi Hand',
    'Fredoka One',
    'Righteous',
    'Creepster',
    'Bungee',
    'Staatliches',
    'Archivo Black',
]

def get_product_by_id(product_id):
    """Get a product by its ID"""
    for product in products:
        if product['id'] == product_id:
            return product
    return None