"""
Static product data migrated from PHP data files
"""

# Products data
products = [
    {
        'id': 0,
        'name': 'Pro Series Hoodie (Fleece Lined) FULL ZIP',
        'modelLink': '/static/models/pro-series-hoodie-full-zip.glb',
        'thumbnail': '/static/thumbnails/pro-series-hoodie-full-zip.png',
        'categories': ['Hoodies'],
        'description': 'Premium fleece-lined hoodie with full zip and customizable pockets. Perfect for staying warm while showcasing your custom designs.',
        'initialLayer': 'Front',
        'canOrder': True,
        'sizes': [
            'Youth Small', 'Youth Medium', 'Youth Large', 'Youth X-Large',
            'X-Small', 'Small', 'Medium', 'Large', 'X-Large',
            '2X-Large', '3X-Large', '4X-Large',
        ],
        'prices': {
            1: 100,
            3: 90,
            5: 80,
            10: 70,
            20: 60,
        },
        'initialBumpmap': 'Polyester',
        'supportedBumpmaps': ['Micromesh', 'Polyester'],
        'productDetails': [
            '100% premium cotton blend',
            'Pre-shrunk for perfect fit',
            'Reinforced seams for durability',
            'Machine washable',
            'Long-lasting vibrant colors',
            'Fade-resistant full sublimation'
        ],
        'meshSettings': {
            'Front': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Back', 'Left_Sleeve', 'Right_Sleeve', 'Hood', 'Pockets'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Back': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Front', 'Left_Sleeve', 'Right_Sleeve', 'Hood', 'Pockets'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Hood': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve', 'Pockets'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Left_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Front', 'Back', 'Right_Sleeve', 'Hood', 'Pockets'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Right_Sleeve': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Hood', 'Pockets'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
            'Pockets': {
                'minX': 0, 'maxX': 1, 'minY': 0, 'maxY': 1,
                'initialColor': 'ffffff',
                'bumpMap': True,
                'linkedColors': [],
                'linkedBumpmaps': ['Front', 'Back', 'Left_Sleeve', 'Right_Sleeve', 'Hood'],
                'canSelect': True,
                'canAddImages': True,
                'canChangeColor': True,
                'canChangeBumpmap': True,
            },
        }
    },
    # Add more products here - keeping just one for now for simplicity
]

# Bumpmap textures data
bumpmap_textures = {
    'none': {
        'name': 'No Texture',
        'link': None,
        'thumbnail': '/static/images/no-texture.svg',
        'scale': 0,
        'size': 1,
        'roughness': 1,
        'metalness': 0,
    },
    'Lace': {
        'name': 'Lace',
        'link': '/static/bumpmaps/fabric2.png',
        'scale': 0.3,
        'size': 3,
        'roughness': 0.9,
        'metalness': 0,
        'thumbnail': '/static/bumpmaps/lace_thumbnail.jpg',
    },
    'Lace2': {
        'name': 'Lace Pattern 2',
        'link': '/static/bumpmaps/lace2.png',
        'scale': 0.5,
        'size': 2,
        'roughness': 0.8,
        'metalness': 0,
        'thumbnail': '/static/bumpmaps/lace2_thumbnail.jpg',
    },
    'Lace3': {
        'name': 'Lace Pattern 3',
        'link': '/static/bumpmaps/lace3.png',
        'scale': 0.4,
        'size': 2.5,
        'roughness': 0.85,
        'metalness': 0,
        'thumbnail': '/static/bumpmaps/lace3_thumbnail.jpg',
    },
    'Cloth': {
        'name': 'Upholstery Cloth',
        'link': '/static/bumpmaps/grey-upholstery_height.png',
        'thumbnail': '/static/bumpmaps/grey-upholstery_height.png',
        'scale': 0.2,
        'size': 4,
        'roughness': 0.95,
        'metalness': 0,
    },
    'Fabric': {
        'name': 'Basic Fabric',
        'link': '/static/bumpmaps/fabric.png',
        'thumbnail': '/static/bumpmaps/fabric.png',
        'scale': 0.25,
        'size': 3.5,
        'roughness': 0.9,
        'metalness': 0,
    },
    'Fabric3': {
        'name': 'Fabric Pattern',
        'link': '/static/bumpmaps/fabric3.png',
        'thumbnail': '/static/bumpmaps/fabric3_thumbnail.jpg',
        'scale': 0.3,
        'size': 3,
        'roughness': 0.85,
        'metalness': 0,
    },
    'Polyester': {
        'name': 'Polyester',
        'link': '/static/bumpmaps/polyester.png',
        'thumbnail': '/static/bumpmaps/polyester_thumbnail.jpg',
        'scale': 0.18,
        'size': 4.5,
        'roughness': 0.75,
        'metalness': 0.1,
    },
    'Polyester2': {
        'name': 'Polyester 2',
        'link': '/static/bumpmaps/polyester2.png',
        'thumbnail': '/static/bumpmaps/polyester2_thumbnail.jpg',
        'scale': 0.2,
        'size': 4,
        'roughness': 0.7,
        'metalness': 0.05,
    },
    'Metal': {
        'name': 'Metal',
        'link': '/static/bumpmaps/metal.png',
        'thumbnail': '/static/bumpmaps/metal_thumbnail.jpg',
        'scale': 0.1,
        'size': 5,
        'roughness': 0.3,
        'metalness': 0.8,
    },
    'Marble': {
        'name': 'Marble',
        'link': '/static/bumpmaps/marble.png',
        'thumbnail': '/static/bumpmaps/marble.png',
        'scale': 0.08,
        'size': 6,
        'roughness': 0.2,
        'metalness': 0.05,
    },
    'Wood': {
        'name': 'Wood',
        'link': '/static/bumpmaps/wood.png',
        'thumbnail': '/static/bumpmaps/wood_thumbnail.jpg',
        'scale': 0.15,
        'size': 4,
        'roughness': 0.8,
        'metalness': 0,
    },
    'Burlap': {
        'name': 'Burlap',
        'link': '/static/bumpmaps/burlap.png',
        'thumbnail': '/static/bumpmaps/burlap_thumbnail.jpg',
        'scale': 0.35,
        'size': 2.5,
        'roughness': 0.95,
        'metalness': 0,
    },
    'Hedge': {
        'name': 'Hedge',
        'link': '/static/bumpmaps/hedge.png',
        'thumbnail': '/static/bumpmaps/hedge_thumbnail.jpg',
        'scale': 0.3,
        'size': 3,
        'roughness': 0.9,
        'metalness': 0,
    },
    'Honeycomb': {
        'name': 'Honeycomb',
        'link': '/static/bumpmaps/honeycomb.png',
        'thumbnail': '/static/bumpmaps/honeycomb_thumbnail.png',
        'scale': 0.25,
        'size': 3.5,
        'roughness': 0.6,
        'metalness': 0.2,
    },
    'Knitted': {
        'name': 'Knitted',
        'link': '/static/bumpmaps/knitted.png',
        'thumbnail': '/static/bumpmaps/knitted_thumbnail.jpg',
        'scale': 0.3,
        'size': 3,
        'roughness': 0.9,
        'metalness': 0,
    },
    'Micromesh': {
        'name': 'Micromesh',
        'link': '/static/bumpmaps/micromesh.png',
        'thumbnail': '/static/bumpmaps/micromesh_thumbnail.jpg',
        'scale': 0.4,
        'size': 2.5,
        'roughness': 0.85,
        'metalness': 0.05,
    },
    'Military': {
        'name': 'Military',
        'link': '/static/bumpmaps/military.png',
        'thumbnail': '/static/bumpmaps/military_thumbnail.jpg',
        'scale': 0.22,
        'size': 3.8,
        'roughness': 0.8,
        'metalness': 0,
    },
    'Nylon': {
        'name': 'Nylon',
        'link': '/static/bumpmaps/nylon.png',
        'thumbnail': '/static/bumpmaps/nylon.png',
        'scale': 0.28,
        'size': 3.2,
        'roughness': 0.7,
        'metalness': 0.1,
    },
}

# Fonts data
fonts = [
    'Roboto',
    'Oswald',
    'Bebas Neue',
    'Anton',
    'Caveat',
    'Permanent Marker',
    'Orbitron',
    'Yellowtail',
    'Bangers',
    'Faster One',
    'Racing Sans One',
    'Rubik Moonrocks',
    'DM Serif Text',
    'Dancing Script',
    'Seymour One',
    'Black Ops One',
    'Shrikhand',
    'Yatra One',
    'Alex Brush',
    'Pacifico',
    'Kaushan Script',
    'Rock Salt',
    'Six Caps',
    'Gochi Hand',
    'Fredoka One',
    'Righteous',
    'Creepster',
    'Bungee',
    'Staatliches',
    'Archivo Black',
]

def get_product_by_id(product_id):
    """Get a product by its ID"""
    for product in products:
        if product['id'] == product_id:
            return product
    return None