# Generated by Django 5.1.11 on 2025-08-22 12:50

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    ProductCategory = apps.get_model('products', 'ProductCategory')
    for category in ProductCategory.objects.all():
        category.slug = slugify(category.name)
        category.save()


def reverse_populate_slugs(apps, schema_editor):
    pass  # No reverse operation needed


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
