# Generated by Django 5.1.11 on 2025-08-22 13:56

from django.db import migrations, models
import django.db.models.deletion


def create_default_brand_and_migrate_data(apps, schema_editor):
    """Create default brand and migrate existing BrandProduct data"""
    Brand = apps.get_model('brands', 'Brand')
    BrandProduct = apps.get_model('products', 'BrandProduct')
    
    # Create default brand if it doesn't exist
    default_brand, created = Brand.objects.get_or_create(
        is_default=True,
        defaults={
            'name': 'Default Brand',
            'slug': 'default-brand',
            'is_active': True,
        }
    )
    
    # Update all existing BrandProducts to use the default brand
    # (This will be run after adding the brand field)
    pass  # Will be handled in the RunPython operation


def migrate_brandproduct_data(apps, schema_editor):
    """Migrate BrandProduct data to use Brand FK"""
    Brand = apps.get_model('brands', 'Brand')
    BrandProduct = apps.get_model('products', 'BrandProduct')
    
    # Get default brand
    default_brand = Brand.objects.get(is_default=True)
    
    # Update all BrandProducts to use the default brand
    BrandProduct.objects.update(brand=default_brand)


def reverse_migration(apps, schema_editor):
    """Reverse migration - populate brand_name from brand"""
    BrandProduct = apps.get_model('products', 'BrandProduct')
    
    for bp in BrandProduct.objects.all():
        if bp.brand:
            bp.brand_name = bp.brand.name
            bp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('products', '0002_auto_20250822_1250'),
    ]

    operations = [
        # First, create the brand field (nullable initially)
        migrations.AddField(
            model_name='brandproduct',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        
        # Create default brand and populate the brand field
        migrations.RunPython(create_default_brand_and_migrate_data, reverse_migration),
        migrations.RunPython(migrate_brandproduct_data, reverse_migration),
        
        # Make brand field required
        migrations.AlterField(
            model_name='brandproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        
        # Update unique constraint
        migrations.AlterUniqueTogether(
            name='brandproduct',
            unique_together={('product', 'brand')},
        ),
        
        # Remove old brand_name field
        migrations.RemoveField(
            model_name='brandproduct',
            name='brand_name',
        ),
        
        # Update model options
        migrations.AlterModelOptions(
            name='brandproduct',
            options={'verbose_name': 'Brand Product', 'verbose_name_plural': 'Brand Products'},
        ),
    ]
